@server = https://hypebuggy-supreme-tribble-5676pvjxrw5fvv5v-8080.preview.app.github.dev
@emp = {{server}}/api/employees
###
GET {{emp}}
###
POST {{emp}}
Content-Type: application/json

{
    "firstName": "Bilbo",
    "lastName": "Baggins",
    "description": "burglar" 
}