@server = https://hypebuggy-supreme-tribble-5676pvjxrw5fvv5v-8081.preview.app.github.dev
@emp = {{server}}/api/emps
###
GET {{emp}}
###
POST {{emp}}
Content-Type: application/json

{
    "firstName": "Hans",
    "lastName": "Limaylla",
    "description": "Estudiante" 
}